name: PR to main workflow

on:
  pull_request:
    branches:
      - main

jobs:
  create_issue:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
    - run: |
        ls -a
        echo "" 
        git branch -a

    - name: Create an issue
      uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
      with:
        assignees: ''
        milestone: ''
        filename: '.github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md'
        update_existing: false
        search_existing: false
