name: PR to main workflow

on:
  pull_request:
    branches:
      - main

jobs:
  create_issue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create an issue
      uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: "New issue from PR to main"
        body: "An issue created automatically when a PR is made to the main branch."
        repo: "nagase-shunsuke-za/try-actions"
