name: tset_and_build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: npm install
        run: npm install
      - name: test & build
        id: build
        run:  |
          npm run test
          npm run build
          git add -N .
          echo "::set-output name=count::$(git diff --name-only | wc -l)"
      - name: commit & push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "push build file"
          git push
        if: steps.build.outputs.count > 0
      - name: deploy
        env:
          DEPLOY_URL: ${{ secrets.DEPLOY_URL }}
        run: echo $DEPLOY_URL
      - name: upload dist file
        uses: actions/upload-artifact@v3
        with:
          name: upload dist file
          path: dist
